#!/bin/bash
# chkconfig: 345 95 20
# Author: Vinod Padarthi
# Description:  DP Service Startup Script
# ProcessName:  dpprocess
# Version : 1.0 Relased Date : 01-06-2014
PATH=$PATH:/bin:/usr/bin:xxx
export PATH

if ! [ "$(/usr/bin/id -u)" = 0 ]; then
   echo "`id -u -n` is not a root user.  $0 must be run as root"
   exit 1
fi

DPPATH="/iqs/DataProcessor/"
cd $DPPATH

if [ -d "$DPPATH" ]
then
echo -e "\e[1;32;40m DP Process Path Available \e[0m"
else
echo -e "\e[1;31;40m Problem With the DP Process Path, Please verify the Path and try again \e[0m"
exit 0
fi
JAVAP="/iqs/java/bin/java"
MINMEM="2048"
MAXMEM="2048"
CPU="1"

if [ -f "$JAVAP" ]
then
echo -e "\e[1;32;40m Java Path Available \e[0m"
else
echo -e "\e[1;31;40m Problem With the Java Path, Please verify the Path and try again \e[0m"
exit 0
fi

parameter () {
echo -e "\e[1;31;40m Memory Parameters : MINMEM=$MINMEM, MAXMEM=$MAXMEM \e[0m"
echo -e "\e[1;31;40m Total CPU Allocated : $CPU \e[0m"
}

mail () {
IPADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`
}

start () {
	
	SERSTATUS=`ps -eaf | grep -w "DataProcessor.jar" | grep -v grep | wc -l`
	if [ $SERSTATUS -eq 1 ] ; then
		echo ""
		echo -e "\e[1;31;40m DP Service Already Running \e[0m"
		echo ""
	else
		parameter
		cd $DPPATH
                nohup $JAVAP -Xms"$MINMEM"m -Xmx"$MAXMEM"m -jar DataProcessor.jar &
                nohup date
                nohup echo "Service Restarted..."
		sleep 5
		SERSTATUS1=`ps -eaf | grep -w "DataProcessor.jar" | grep -v grep | wc -l`
		if [ $SERSTATUS1 -eq 1 ] ; then
			echo ""
			echo -e "\e[1;32;40m DP Service Started Successfully. \e[0m"
			echo ""
		else
			echo ""
			echo -e "\e[1;31;40m Error Starting the DP Service. \e[0m"
			echo ""
		fi
	fi
}

stop () {
	SERPID=`ps -eaf | grep -w "DataProcessor.jar" | grep -v grep | wc -l`
	if [ $SERPID -eq 0 ]
		then
		echo ""
		echo -e "\e[1;31;40m DP Service Already Stopped. \e[0m"
		echo ""
	else
		SERPID1=`ps -eaf | grep -w "DataProcessor.jar" | grep -v grep | awk '{print $2}'`
		kill $SERPID1
		sleep 5
		SERPID=`ps -eaf | grep -w "DataProcessor.jar" | grep -v grep | wc -l`
		if [ $SERPID -eq 0 ] ; then
			echo ""
			echo -e "\e[1;32;40m DP Service Stopped Successfully. \e[0m"
			echo ""
		else
		SERPID1=`ps -eaf | grep -w "DataProcessor.jar" | grep -v grep | awk '{print $2}'`
                kill -9 $SERPID1
                sleep 5
		SERPID=`ps -eaf | grep -w "DataProcessor.jar" | grep -v grep | wc -l`
                if [ $SERPID -eq 0 ] ; then
                        echo ""
                        echo -e "\e[1;32;40m DP Service Stopped Successfully. \e[0m"
                        echo ""
                else
                        echo ""
                        echo -e "\e[1;31;40m Error Stopping DP Service. \e[0m"
                        echo ""
                fi
		fi
	fi
}

restart () {
stop
sleep 2
start
}

status () {
	SERSTATUS=`ps -eaf | grep -w "DataProcessor.jar" | grep -v grep | wc -l`
	if [ $SERSTATUS -eq 1 ]
		then
		echo ""
	        echo -e "DP Service Running"
	        #echo -e "\e[1;32;40m DP Service Running \e[0m"
		echo ""
	else
		echo ""
		echo -e "DP Service Stopped"
		#echo -e "\e[1;31;40m DP Service Stopped \e[0m"
		echo ""
	fi
}


case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	status)
		status
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac
