#!/bin/bash
# chkconfig: 345 95 20
# Author: Thangapandi
# Description:  ATDM DATA IMPORTER Service Startup Script
# ProcessName:  ATDMDataimporter

if ! [ $(id -u) = 0 ]; then
   echo "`id -u -n` is not a root user.  $0 must be run as root"
   exit 1
fi


ATDMPATH="/iqs/ATDMDataImporter"
cd $ATDMPATH

if [ -d "$ATDMPATH" ]
then
echo -e "\e[1;32;40m ATDM DATA Process Path Available \e[0m"
else
echo -e "\e[1;31;40m Problem With the ATDM DATA Process Path, Please verify the Path and try again \e[0m"
exit 0
fi
JAVAP="/iqs/java/bin/java"

if [ -f "$JAVAP" ]
then
echo -e "\e[1;32;40m Java Path Available \e[0m"
else
echo -e "\e[1;31;40m Problem With the Java Path, Please verify the Path and try again \e[0m"
exit 0
fi


mail () {
IPADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`
}

start () {
	
	SERSTATUS=`ps -eaf | grep -w "ATDMDataImporter.jar" | grep -v grep | wc -l`
	if [ $SERSTATUS -eq 1 ] ; then
		echo ""
		echo -e "\e[1;31;40m ATDM DATA IMPORTER Service Already Running \e[0m"
		echo ""
	else
		cd $ATDMPATH
		nohup $JAVAP -jar ATDMDataImporter.jar &
		nohup date 
		nohup echo "Service Restarted..."
		sleep 10
		SERSTATUS1=`ps -eaf | grep -w "ATDMDataImporter.jar" | grep -v grep | wc -l`
		if [ $SERSTATUS1 -eq 1 ] ; then
			echo ""
			echo -e "\e[1;32;40m ATDM DATA IMPORTER Service Started Successfully. \e[0m"
			echo ""
		else
			echo ""
			echo -e "\e[1;31;40m Error Starting the ATDM DATA IMPORTER Service. \e[0m"
			echo ""
		fi
	fi
}


stop () {
	SERPID=`ps -eaf | grep -w "ATDMDataImporter.jar" | grep -v grep | wc -l`
	if [ $SERPID -eq 0 ]
		then
		echo ""
		echo -e "\e[1;31;40m ATDM DATA IMPORTER Service Already Stopped. \e[0m"
		echo ""
	else
		SERPID1=`ps -eaf | grep -w "ATDMDataImporter.jar" | grep -v grep | awk '{print $2}'`
		kill $SERPID1
		sleep 10
		SERPID=`ps -eaf | grep -w "ATDMDataImporter.jar" | grep -v grep | wc -l`
		if [ $SERPID -eq 0 ] ; then
			echo ""
			echo -e "\e[1;32;40m ATDM DATA IMPORTER Service Stopped Successfully. \e[0m"
			echo ""
		else
		SERPID1=`ps -eaf | grep -w "ATDMDataImporter.jar" | grep -v grep | awk '{print $2}'`
                kill -9 $SERPID1
		sleep 10
                SERPID=`ps -eaf | grep -w "ATDMDataImporter.jar" | grep -v grep | wc -l`
                if [ $SERPID -eq 0 ] ; then
                        echo ""
                        echo -e "\e[1;32;40m ATDM DATA IMPORTER Service Stopped Successfully. \e[0m"
                        echo ""
                else
                        echo ""
                        echo -e "\e[1;31;40m Error Stopping ATDM DATA IMPORTER Service. \e[0m"
                        echo ""
                fi
		fi
	fi
}

restart () {
stop
sleep 2
start
}

status () {
	SERSTATUS=`ps -eaf | grep -w "ATDMDataImporter.jar" | grep -v grep | wc -l`
	if [ $SERSTATUS -eq 1 ]
		then
		echo ""
		echo -e "\e[1;32;40m ATDM DATA IMPORTER Service Running \e[0m"
		echo ""
	else
		echo ""
		echo -e "\e[1;31;40m ATDM DATA IMPORTER Service Stopped \e[0m"
		echo ""
	fi
}


case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	status)
		status
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac
