#!/bin/bash
# chkconfig: 345 95 20
# Author: Vinod Padarthi
# Description:  GW Service Startup Script
# ProcessName:  siqgw
# Version : 1.0 Relased Date : 01-06-2014
PATH=$PATH:/bin:/usr/bin:xxx
export PATH

if ! [ "$(/usr/bin/id -u)" = 0 ]; then
   echo "`id -u -n` is not a root user.  $0 must be run as root"
   exit 1
fi

GWPATH="/iqs/GatewayServer"
cd $GWPATH

if [ -d "$GWPATH" ]
then
echo -e "\e[1;32;40m GW Process Path Available \e[0m"
else
echo -e "\e[1;31;40m Problem With the GW Process Path, Please verify the Path and try again \e[0m"
exit 0
fi
JAVAP="/iqs/java/bin/java"
MINMEM="2048"
MAXMEM="2048"
CPU="1"
JOPT="-XX:+UseG1GC"


if [ -f "$JAVAP" ]
then
echo -e "\e[1;32;40m Java Path Available \e[0m"
else
echo -e "\e[1;31;40m Problem With the Java Path, Please verify the Path and try again \e[0m"
exit 0
fi

parameter () {
echo -e "\e[1;31;40m Memory Parameters : MINMEM=$MINMEM, MAXMEM=$MAXMEM \e[0m"
echo -e "\e[1;31;40m Total CPU Allocated : $CPU \e[0m"
}

mail () {
IPADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`
}

start () {
	
	SERSTATUS=`ps -eaf | grep -w "GatewayServer.jar" | grep -v grep | wc -l`
	if [ $SERSTATUS -eq 1 ] ; then
		echo ""
		echo -e "\e[1;31;40m GW Service Already Running \e[0m"
		echo ""
	else
		parameter
		cd $GWPATH
		#taskset -c $CPU nohup $JAVAP -Xms"$MINMEM"m -Xmx"$MAXMEM"m -jar GatewayServer.jar &
		nohup $JAVAP -Xms"$MINMEM"m -Xmx"$MAXMEM"m "$JOPT" -jar GatewayServer.jar &
                nohup date
                nohup echo "Service Restarted..."
		sleep 10
		SERSTATUS1=`ps -eaf | grep -w "GatewayServer.jar" | grep -v grep | wc -l`
		if [ $SERSTATUS1 -eq 1 ] ; then
			echo ""
			echo -e "\e[1;32;40m GW Service Started Successfully. \e[0m"
			echo ""
		else
			echo ""
			echo -e "\e[1;31;40m Error Starting the GW Service. \e[0m"
			echo ""
		fi
	fi
}


stop () {
	SERPID=`ps -eaf | grep -w "GatewayServer.jar" | grep -v grep | wc -l`
	if [ $SERPID -eq 0 ]
		then
		echo ""
		echo -e "\e[1;31;40m GW Service Already Stopped. \e[0m"
		echo ""
	else
		SERPID1=`ps -eaf | grep -w "GatewayServer.jar" | grep -v grep | awk '{print $2}'`
		kill $SERPID1
		sleep 10
		SERPID=`ps -eaf | grep -w "GatewayServer.jar" | grep -v grep | wc -l`
		if [ $SERPID -eq 0 ] ; then
			echo ""
			echo -e "\e[1;32;40m GW Service Stopped Successfully. \e[0m"
			echo ""
		else
		SERPID1=`ps -eaf | grep -w "GatewayServer.jar" | grep -v grep | awk '{print $2}'`
                kill -9 $SERPID1
		sleep 10
                SERPID=`ps -eaf | grep -w "GatewayServer.jar" | grep -v grep | wc -l`
                if [ $SERPID -eq 0 ] ; then
                        echo ""
                        echo -e "\e[1;32;40m GW Service Stopped forcefully. \e[0m"
                        echo ""
                else
                        echo ""
                        echo -e "\e[1;31;40m Error Stopping GW Service. \e[0m"
                        echo ""
                fi
		fi
	fi
}

restart () {
stop
sleep 2
start
}

status () {
	SERSTATUS=`ps -eaf | grep -w "GatewayServer.jar" | grep -v grep | wc -l`
	if [ $SERSTATUS -eq 1 ]
		then
		echo ""
		echo -e "GW Service Running"
		#echo -e "\e[1;32;40m GW Service Running \e[0m"
		echo ""
	else
		echo ""
		echo -e "GW Service Stopped"
		#echo -e "\e[1;31;40m GW Service Stopped \e[0m"
		echo ""
	fi
}


case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	status)
		status
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac
